using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Contractposition
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public string CalcRule { get; set; }
        public string Carrier { get; set; }
        public int Category { get; set; }
        public int Contact { get; set; }
        public short? ContractPositionState { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public string Description { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public decimal? Discount { get; set; }
        public string DiscountDescription { get; set; }
        public bool? DiscountIsPercentage { get; set; }
        public int ExternalLink { get; set; }
        public string GiftMessage { get; set; }
        public string PParent { get; set; }
        public bool? IsGift { get; set; }
        public long? LineItemNumber { get; set; }
        public string ListPrice { get; set; }
        public decimal? MaxQuantity { get; set; }
        public short? MinMaxQuantityHandling { get; set; }
        public decimal? MinQuantity { get; set; }
        public int ModifiedBy { get; set; }
        public string Name { get; set; }
        public decimal? OffsetQuantity { get; set; }
        public int Owner { get; set; }
        public string PositionNumber { get; set; }
        public string PriceLevel { get; set; }
        public decimal? PricePerUnit { get; set; }
        public string PriceUom { get; set; }
        public DateTime? PricingDate { get; set; }
        public string PricingRule { get; set; }
        public short? PricingState { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? SalesCommission { get; set; }
        public bool? SalesCommissionIsPercentage { get; set; }
        public string SalesTaxType { get; set; }
        public string ShippingInstructions { get; set; }
        public short? ShippingMethod { get; set; }
        public string ShippingTrackingNumber { get; set; }
        public string Uom { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public string ConfigType { get; set; }
        public string CurrentConfig { get; set; }
        public string Product { get; set; }
        public int ProductSerialNumber { get; set; }
        public short? CloseProbability { get; set; }
        public DateTime? EstimatedCloseDate { get; set; }
        public int? Budget { get; set; }
        public bool? ExtBoolean0 { get; set; }
        public bool? ExtBoolean1 { get; set; }
        public bool? ExtBoolean2 { get; set; }
        public bool? ExtBoolean3 { get; set; }
        public bool? ExtBoolean4 { get; set; }
        public short? ExtCode0 { get; set; }
        public short? ExtCode1 { get; set; }
        public short? ExtCode2 { get; set; }
        public short? ExtCode3 { get; set; }
        public short? ExtCode4 { get; set; }
        public DateTime? ExtDate0 { get; set; }
        public DateTime? ExtDate1 { get; set; }
        public DateTime? ExtDate2 { get; set; }
        public DateTime? ExtDate3 { get; set; }
        public DateTime? ExtDate4 { get; set; }
        public DateTime? ExtDateTime0 { get; set; }
        public DateTime? ExtDateTime1 { get; set; }
        public DateTime? ExtDateTime2 { get; set; }
        public DateTime? ExtDateTime3 { get; set; }
        public DateTime? ExtDateTime4 { get; set; }
        public decimal? ExtNumber0 { get; set; }
        public decimal? ExtNumber1 { get; set; }
        public decimal? ExtNumber2 { get; set; }
        public decimal? ExtNumber3 { get; set; }
        public decimal? ExtNumber4 { get; set; }
        public string ExtString0 { get; set; }
        public string ExtString1 { get; set; }
        public string ExtString2 { get; set; }
        public string ExtString3 { get; set; }
        public string ExtString4 { get; set; }
        public int? SalesVolContract { get; set; }
        public string SalesTransactionType { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
        public string Origin { get; set; }
        public short? DiscountCalculationType { get; set; }
        public string DiscountOrigin { get; set; }
        public bool? ManualPricing { get; set; }
    }
}
