using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Address
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public string PParent { get; set; }
        public string Building { get; set; }
        public int Category { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public int ExternalLink { get; set; }
        public bool? IsMain { get; set; }
        public int ModifiedBy { get; set; }
        public int Owner { get; set; }
        public int Objusage { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public string WebUrl { get; set; }
        public string Picture { get; set; }
        public string PostalAddressLine0 { get; set; }
        public string PostalAddressLine1 { get; set; }
        public string PostalAddressLine2 { get; set; }
        public string PostalAddressLine3 { get; set; }
        public string PostalAddressLine4 { get; set; }
        public string PostalCity { get; set; }
        public string PostalCode { get; set; }
        public short? PostalCountry { get; set; }
        public string PostalCounty { get; set; }
        public short? PostalFreightTerms { get; set; }
        public decimal? PostalLatitude { get; set; }
        public decimal? PostalLongitude { get; set; }
        public string PostalState { get; set; }
        public string PostalStreetNumber { get; set; }
        public string PostalStreet0 { get; set; }
        public string PostalStreet1 { get; set; }
        public string PostalStreet2 { get; set; }
        public string PostalStreet3 { get; set; }
        public string PostalStreet4 { get; set; }
        public short? PostalUtcOffset { get; set; }
        public bool? AutomaticParsing { get; set; }
        public string PhoneCityArea { get; set; }
        public short? PhoneCountryPrefix { get; set; }
        public string PhoneExtension { get; set; }
        public string PhoneLocalNumber { get; set; }
        public string PhoneNumberFull { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
        public short? EmailFormat { get; set; }
        public short? EmailType { get; set; }
        public string RoomNumber { get; set; }
        public DateTime? ValidTo { get; set; }
        public DateTime? ValidFrom { get; set; }
        public string Authority { get; set; }
        public string Tz { get; set; }
        public string Region1 { get; set; }
        public string Region2 { get; set; }
        public string Region3 { get; set; }
        public string RegionType1 { get; set; }
        public string RegionType2 { get; set; }
        public string RegionType3 { get; set; }
        public string Description { get; set; }
        public string SalutationForCorrespondance { get; set; }
        public string PostalCodeAddOn { get; set; }
        public string PostalCodeId { get; set; }
        public string UriAuthority { get; set; }
        public string UriFragment { get; set; }
        public string UriHost { get; set; }
        public string UriPath { get; set; }
        public string UriPort { get; set; }
        public string UriQuery { get; set; }
        public string UriReference { get; set; }
        public string UriScheme { get; set; }
        public string UriSchemeSpecificPart { get; set; }
        public string UriUserInfo { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
        public string MunicipalityId { get; set; }
        public string MunicipalityName { get; set; }
    }
}
