using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Account
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public int AccountCategory { get; set; }
        public short? AccountRating { get; set; }
        public short? AccountState { get; set; }
        public int AccountType { get; set; }
        public string AliasName { get; set; }
        public int BusinessType { get; set; }
        public int Category { get; set; }
        public int Contact { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public string Description { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public bool? ExtBoolean0 { get; set; }
        public bool? ExtBoolean1 { get; set; }
        public bool? ExtBoolean2 { get; set; }
        public bool? ExtBoolean3 { get; set; }
        public bool? ExtBoolean4 { get; set; }
        public bool? ExtBoolean5 { get; set; }
        public bool? ExtBoolean6 { get; set; }
        public bool? ExtBoolean7 { get; set; }
        public bool? ExtBoolean8 { get; set; }
        public bool? ExtBoolean9 { get; set; }
        public short? ExtCode0 { get; set; }
        public short? ExtCode1 { get; set; }
        public short? ExtCode10 { get; set; }
        public short? ExtCode11 { get; set; }
        public short? ExtCode12 { get; set; }
        public short? ExtCode13 { get; set; }
        public short? ExtCode14 { get; set; }
        public short? ExtCode15 { get; set; }
        public short? ExtCode16 { get; set; }
        public short? ExtCode17 { get; set; }
        public short? ExtCode18 { get; set; }
        public short? ExtCode19 { get; set; }
        public short? ExtCode2 { get; set; }
        public int ExtCode20 { get; set; }
        public int ExtCode21 { get; set; }
        public int ExtCode22 { get; set; }
        public int ExtCode23 { get; set; }
        public int ExtCode24 { get; set; }
        public int ExtCode25 { get; set; }
        public int ExtCode26 { get; set; }
        public int ExtCode27 { get; set; }
        public int ExtCode28 { get; set; }
        public int ExtCode29 { get; set; }
        public short? ExtCode3 { get; set; }
        public short? ExtCode4 { get; set; }
        public short? ExtCode5 { get; set; }
        public short? ExtCode6 { get; set; }
        public short? ExtCode7 { get; set; }
        public short? ExtCode8 { get; set; }
        public short? ExtCode9 { get; set; }
        public DateTime? ExtDate0 { get; set; }
        public DateTime? ExtDate1 { get; set; }
        public DateTime? ExtDate2 { get; set; }
        public DateTime? ExtDate3 { get; set; }
        public DateTime? ExtDate4 { get; set; }
        public DateTime? ExtDate5 { get; set; }
        public DateTime? ExtDate6 { get; set; }
        public DateTime? ExtDate7 { get; set; }
        public DateTime? ExtDate8 { get; set; }
        public DateTime? ExtDate9 { get; set; }
        public DateTime? ExtDateTime0 { get; set; }
        public DateTime? ExtDateTime1 { get; set; }
        public DateTime? ExtDateTime2 { get; set; }
        public DateTime? ExtDateTime3 { get; set; }
        public DateTime? ExtDateTime4 { get; set; }
        public DateTime? ExtDateTime5 { get; set; }
        public DateTime? ExtDateTime6 { get; set; }
        public DateTime? ExtDateTime7 { get; set; }
        public DateTime? ExtDateTime8 { get; set; }
        public DateTime? ExtDateTime9 { get; set; }
        public decimal? ExtNumber0 { get; set; }
        public decimal? ExtNumber1 { get; set; }
        public decimal? ExtNumber2 { get; set; }
        public decimal? ExtNumber3 { get; set; }
        public decimal? ExtNumber4 { get; set; }
        public decimal? ExtNumber5 { get; set; }
        public decimal? ExtNumber6 { get; set; }
        public decimal? ExtNumber7 { get; set; }
        public decimal? ExtNumber8 { get; set; }
        public decimal? ExtNumber9 { get; set; }
        public string ExtString0 { get; set; }
        public string ExtString1 { get; set; }
        public string ExtString2 { get; set; }
        public string ExtString3 { get; set; }
        public string ExtString4 { get; set; }
        public string ExtString5 { get; set; }
        public string ExtString6 { get; set; }
        public string ExtString7 { get; set; }
        public string ExtString8 { get; set; }
        public string ExtString9 { get; set; }
        public int ExternalLink { get; set; }
        public string FullName { get; set; }
        public string Master { get; set; }
        public int ModifiedBy { get; set; }
        public int Owner { get; set; }
        public int Partner { get; set; }
        public string PParent { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public short? Industry { get; set; }
        public string Name { get; set; }
        public int? NumberOfEmployees { get; set; }
        public short? NumberOfEmployeesCategory { get; set; }
        public string OrgUnit { get; set; }
        public string StockExchange { get; set; }
        public string TickerSymbol { get; set; }
        public DateTime? Anniversary { get; set; }
        public decimal? AnnualIncomeAmount { get; set; }
        public short? AnnualIncomeCurrency { get; set; }
        public string Assistant { get; set; }
        public DateTime? Birthdate { get; set; }
        public int ChildrenNames { get; set; }
        public int Citizenship { get; set; }
        public string Department { get; set; }
        public string Deputy { get; set; }
        public bool? DoNotBulkPostalMail { get; set; }
        public bool? DoNotEMail { get; set; }
        public bool? DoNotFax { get; set; }
        public bool? DoNotPhone { get; set; }
        public bool? DoNotPostalMail { get; set; }
        public short? Education { get; set; }
        public short? FamilyStatus { get; set; }
        public string FirstName { get; set; }
        public short? Gender { get; set; }
        public string GovernmentId { get; set; }
        public string JobRole { get; set; }
        public string JobTitle { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string NickName { get; set; }
        public short? NumberOfChildren { get; set; }
        public string Organization { get; set; }
        public string Picture { get; set; }
        public short? PreferredContactMethod { get; set; }
        public short? PreferredSpokenLanguage { get; set; }
        public short? PreferredWrittenLanguage { get; set; }
        public int Religion { get; set; }
        public string ReportsTo { get; set; }
        public string Salutation { get; set; }
        public short? SalutationCode { get; set; }
        public string Suffix { get; set; }
        public string Vcard { get; set; }
        public string Closing { get; set; }
        public short? ClosingCode { get; set; }
        public DateTime? DateOfDeath { get; set; }
        public DateTime? DissolvedAt { get; set; }
        public DateTime? EstablishedAt { get; set; }
        public string OriginalName { get; set; }
        public string SearchEmail1 { get; set; }
        public string SearchEmail2 { get; set; }
        public string SearchMobile1 { get; set; }
        public string SearchMobile2 { get; set; }
        public string SearchPhone1 { get; set; }
        public string SearchPhone2 { get; set; }
        public string SearchPostal1City { get; set; }
        public short? SearchPostal1Country { get; set; }
        public string SearchPostal1PostalCode { get; set; }
        public string SearchPostal1State { get; set; }
        public string SearchPostal1StreetNumber { get; set; }
        public string SearchPostal2City { get; set; }
        public short? SearchPostal2Country { get; set; }
        public string SearchPostal2PostalCode { get; set; }
        public string SearchPostal2State { get; set; }
        public string SearchPostal2StreetNumber { get; set; }
        public string SearchPostal1AddressLine { get; set; }
        public string SearchPostal1Street { get; set; }
        public string SearchPostal2AddressLine { get; set; }
        public string SearchPostal2Street { get; set; }
        public string SearchName { get; set; }
        public string PlaceOfBirth { get; set; }
        public string PlaceOfDeath { get; set; }
        public string PlaceOfOrigin { get; set; }
        public string ActivityTracker { get; set; }
        public string AdditionalName1 { get; set; }
        public string AdditionalName2 { get; set; }
        public string ContractGroup { get; set; }
        public string DocumentFolder { get; set; }
        public string GroupType { get; set; }
        public string CompanyApprenticeshipNo { get; set; }
        public string CompanyType { get; set; }
        public string VatNumber { get; set; }
        public string Institution { get; set; }
        public int? KlassNiveau { get; set; }
        public string KlassState { get; set; }
        public string KlassType { get; set; }
        public int? MaxMembers { get; set; }
        public int? MinMembers { get; set; }
        public string SearchCourseSequences { get; set; }
        public string SearchEducationLevels { get; set; }
        public DateTime? SearchKlassEndAt { get; set; }
        public DateTime? SearchKlassStartAt { get; set; }
        public string SearchKlassState { get; set; }
        public string SearchKlassType { get; set; }
        public int? SearchMemberCountF { get; set; }
        public int? SearchMemberCountM { get; set; }
        public int? SearchMemberCountTotal { get; set; }
        public string SearchSubjectTables { get; set; }
        public string SearchTeachers { get; set; }
        public string AccountingCompanyCode { get; set; }
        public string DepotHolder { get; set; }
        public string EsrCodePattern { get; set; }
        public DateTime? CompulsorySchoolAttendanceEndAt { get; set; }
        public DateTime? CompulsorySchoolAttendanceStartAt { get; set; }
        public string FirstNamePassport { get; set; }
        public string LastNamePassport { get; set; }
        public int? QualificationType { get; set; }
        public DateTime? RecalculatedAssessmentsAt { get; set; }
        public string ReligionType { get; set; }
        public string ResidencePermit { get; set; }
        public string SearchContractTypes { get; set; }
        public string SearchOrganisationNames { get; set; }
        public string SearchQualificationTypes { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
        public string AccountNumber { get; set; }
        public string ShisCode { get; set; }
        public DateTime? MusicSchoolAttendanceEndAt { get; set; }
        public DateTime? MusicSchoolAttendanceStartAt { get; set; }
    }
}
