using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Paymentrecord
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public int? Category { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? CreatedBy { get; set; }
        public string Description { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public DateTime? DueBy { get; set; }
        public int? ExternalLink { get; set; }
        public int? ModifiedBy { get; set; }
        public string Name { get; set; }
        public decimal? OriginalAmount { get; set; }
        public short? OriginalCurrency { get; set; }
        public int? Owner { get; set; }
        public short? PaymentType { get; set; }
        public decimal? ReceivedAmount { get; set; }
        public DateTime? ReceivedAt { get; set; }
        public string ReferenceNumber { get; set; }
        public decimal? RequestedAmount { get; set; }
        public DateTime? RequestedAt { get; set; }
        public string PParent { get; set; }
        public short? Status { get; set; }
        public string TransactionHeader { get; set; }
        public string TransactionNumber { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int? UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int? UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int? UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int? UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int? UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int? UserString4 { get; set; }
        public string Dtype { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
        public string Pain1CdtrAcctCcy { get; set; }
        public string Pain1CdtrAcctId { get; set; }
        public string Pain1CdtrAcctNm { get; set; }
        public string Pain1CdtrAcctTp { get; set; }
        public string Pain1CdtrAgtAcctCcy { get; set; }
        public string Pain1CdtrAgtAcctId { get; set; }
        public string Pain1CdtrAgtAcctTp { get; set; }
        public string Pain1CdtrAgtBrnchId { get; set; }
        public string Pain1CdtrAgtBrnchNm { get; set; }
        public int? Pain1CdtrAgtBrnchPstlAdrAdrLine { get; set; }
        public string Pain1CdtrAgtBrnchPstlAdrBldgNb { get; set; }
        public string Pain1CdtrAgtBrnchPstlAdrCtry { get; set; }
        public string Pain1CdtrAgtBrnchPstlAdrPstCd { get; set; }
        public string Pain1CdtrAgtBrnchPstlAdrStrtNm { get; set; }
        public string Pain1CdtrAgtBrnchPstlAdrTwnNm { get; set; }
        public string Pain1CdtrAgtFinInstnId { get; set; }
        public string Pain1CdtrAgtNm { get; set; }
        public string Pain1CdtrCtryOfRes { get; set; }
        public string Pain1CdtrId { get; set; }
        public string Pain1CdtrNm { get; set; }
        public int? Pain1CdtrPstlAdrAdrLine { get; set; }
        public string Pain1CdtrPstlAdrBldgNb { get; set; }
        public string Pain1CdtrPstlAdrCtry { get; set; }
        public string Pain1CdtrPstlAdrPstCd { get; set; }
        public string Pain1CdtrPstlAdrStrtNm { get; set; }
        public string Pain1CdtrPstlAdrTwnNm { get; set; }
        public string Pain1EndToEndId { get; set; }
        public string Pain1InstrId { get; set; }
        public string Pain1RmtInfStrdCdtrRefInfRef { get; set; }
        public string Pain1RmtInfStrdCdtrRefInfTp { get; set; }
        public string Pain1RmtInfUstrd { get; set; }
        public string Pain1UltmtCdtrCtryOfRes { get; set; }
        public string Pain1UltmtCdtrId { get; set; }
        public string Pain1UltmtCdtrNm { get; set; }
        public int? Pain1UltmtCdtrPstlAdrAdrLine { get; set; }
        public string Pain1UltmtCdtrPstlAdrBldgNb { get; set; }
        public string Pain1UltmtCdtrPstlAdrCtry { get; set; }
        public string Pain1UltmtCdtrPstlAdrPstCd { get; set; }
        public string Pain1UltmtCdtrPstlAdrStrtNm { get; set; }
        public string Pain1UltmtCdtrPstlAdrTwnNm { get; set; }
        public string Pain1UltmtDbtrCtryOfRes { get; set; }
        public string Pain1UltmtDbtrId { get; set; }
        public string Pain1UltmtDbtrNm { get; set; }
        public int? Pain1UltmtDbtrPstlAdrAdrLine { get; set; }
        public string Pain1UltmtDbtrPstlAdrBldgNb { get; set; }
        public string Pain1UltmtDbtrPstlAdrCtry { get; set; }
        public string Pain1UltmtDbtrPstlAdrPstCd { get; set; }
        public string Pain1UltmtDbtrPstlAdrStrtNm { get; set; }
        public string Pain1UltmtDbtrPstlAdrTwnNm { get; set; }
    }
}
