using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1AccountPublicKlu
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public int? AccountCategory { get; set; }
        public int AccountRating { get; set; }
        public int AccountState { get; set; }
        public int? AccountType { get; set; }
        public int? AliasName { get; set; }
        public int? BusinessType { get; set; }
        public int? Category { get; set; }
        public int? Contact { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public int? Description { get; set; }
        public bool? Disabled { get; set; }
        public int? DisabledReason { get; set; }
        public int? ExtBoolean0 { get; set; }
        public int? ExtBoolean1 { get; set; }
        public int? ExtBoolean2 { get; set; }
        public int? ExtBoolean3 { get; set; }
        public int? ExtBoolean4 { get; set; }
        public int? ExtBoolean5 { get; set; }
        public int? ExtBoolean6 { get; set; }
        public int? ExtBoolean7 { get; set; }
        public int? ExtBoolean8 { get; set; }
        public int? ExtBoolean9 { get; set; }
        public int? ExtCode0 { get; set; }
        public int? ExtCode1 { get; set; }
        public int? ExtCode10 { get; set; }
        public int? ExtCode11 { get; set; }
        public int? ExtCode12 { get; set; }
        public int? ExtCode13 { get; set; }
        public int? ExtCode14 { get; set; }
        public int? ExtCode15 { get; set; }
        public int? ExtCode16 { get; set; }
        public int? ExtCode17 { get; set; }
        public int? ExtCode18 { get; set; }
        public int? ExtCode19 { get; set; }
        public int? ExtCode2 { get; set; }
        public int? ExtCode20 { get; set; }
        public int? ExtCode21 { get; set; }
        public int? ExtCode22 { get; set; }
        public int? ExtCode23 { get; set; }
        public int? ExtCode24 { get; set; }
        public int? ExtCode25 { get; set; }
        public int? ExtCode26 { get; set; }
        public int? ExtCode27 { get; set; }
        public int? ExtCode28 { get; set; }
        public int? ExtCode29 { get; set; }
        public int? ExtCode3 { get; set; }
        public int? ExtCode4 { get; set; }
        public int? ExtCode5 { get; set; }
        public int? ExtCode6 { get; set; }
        public int? ExtCode7 { get; set; }
        public int? ExtCode8 { get; set; }
        public int? ExtCode9 { get; set; }
        public int? ExtDate0 { get; set; }
        public int? ExtDate1 { get; set; }
        public int? ExtDate2 { get; set; }
        public int? ExtDate3 { get; set; }
        public int? ExtDate4 { get; set; }
        public int? ExtDate5 { get; set; }
        public int? ExtDate6 { get; set; }
        public int? ExtDate7 { get; set; }
        public int? ExtDate8 { get; set; }
        public int? ExtDate9 { get; set; }
        public int? ExtDateTime0 { get; set; }
        public int? ExtDateTime1 { get; set; }
        public int? ExtDateTime2 { get; set; }
        public int? ExtDateTime3 { get; set; }
        public int? ExtDateTime4 { get; set; }
        public int? ExtDateTime5 { get; set; }
        public int? ExtDateTime6 { get; set; }
        public int? ExtDateTime7 { get; set; }
        public int? ExtDateTime8 { get; set; }
        public int? ExtDateTime9 { get; set; }
        public int? ExtNumber0 { get; set; }
        public int? ExtNumber1 { get; set; }
        public int? ExtNumber2 { get; set; }
        public int? ExtNumber3 { get; set; }
        public int? ExtNumber4 { get; set; }
        public int? ExtNumber5 { get; set; }
        public int? ExtNumber6 { get; set; }
        public int? ExtNumber7 { get; set; }
        public int? ExtNumber8 { get; set; }
        public int? ExtNumber9 { get; set; }
        public int? ExtString0 { get; set; }
        public int? ExtString1 { get; set; }
        public int? ExtString2 { get; set; }
        public int? ExtString3 { get; set; }
        public int? ExtString4 { get; set; }
        public int? ExtString5 { get; set; }
        public int? ExtString6 { get; set; }
        public int? ExtString7 { get; set; }
        public int? ExtString8 { get; set; }
        public int? ExtString9 { get; set; }
        public int? ExternalLink { get; set; }
        public int? FullName { get; set; }
        public int? Master { get; set; }
        public int ModifiedBy { get; set; }
        public int? Owner { get; set; }
        public int? Partner { get; set; }
        public string PParent { get; set; }
        public int? UserBoolean0 { get; set; }
        public int? UserBoolean1 { get; set; }
        public int? UserBoolean2 { get; set; }
        public int? UserBoolean3 { get; set; }
        public int? UserBoolean4 { get; set; }
        public int? UserCode0 { get; set; }
        public int? UserCode1 { get; set; }
        public int? UserCode2 { get; set; }
        public int? UserCode3 { get; set; }
        public int? UserCode4 { get; set; }
        public int? UserDate0 { get; set; }
        public int? UserDate1 { get; set; }
        public int? UserDate2 { get; set; }
        public int? UserDate3 { get; set; }
        public int? UserDate4 { get; set; }
        public int? UserDateTime0 { get; set; }
        public int? UserDateTime1 { get; set; }
        public int? UserDateTime2 { get; set; }
        public int? UserDateTime3 { get; set; }
        public int? UserDateTime4 { get; set; }
        public int? UserNumber0 { get; set; }
        public int? UserNumber1 { get; set; }
        public int? UserNumber2 { get; set; }
        public int? UserNumber3 { get; set; }
        public int? UserNumber4 { get; set; }
        public int? UserString0 { get; set; }
        public int? UserString1 { get; set; }
        public int? UserString2 { get; set; }
        public int? UserString3 { get; set; }
        public int? UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public int Industry { get; set; }
        public string Name { get; set; }
        public int? NumberOfEmployees { get; set; }
        public int NumberOfEmployeesCategory { get; set; }
        public int? OrgUnit { get; set; }
        public int? StockExchange { get; set; }
        public int? TickerSymbol { get; set; }
        public int? Anniversary { get; set; }
        public int? AnnualIncomeAmount { get; set; }
        public int? AnnualIncomeCurrency { get; set; }
        public int? Assistant { get; set; }
        public DateTime? Birthdate { get; set; }
        public int? ChildrenNames { get; set; }
        public int? Citizenship { get; set; }
        public int? Department { get; set; }
        public int? Deputy { get; set; }
        public int? DoNotBulkPostalMail { get; set; }
        public int? DoNotEMail { get; set; }
        public int? DoNotFax { get; set; }
        public int? DoNotPhone { get; set; }
        public int? DoNotPostalMail { get; set; }
        public int Education { get; set; }
        public int FamilyStatus { get; set; }
        public string FirstName { get; set; }
        public int Gender { get; set; }
        public string GovernmentId { get; set; }
        public int? JobRole { get; set; }
        public int? JobTitle { get; set; }
        public string LastName { get; set; }
        public int? MiddleName { get; set; }
        public int? NickName { get; set; }
        public int? NumberOfChildren { get; set; }
        public int? Organization { get; set; }
        public int? Picture { get; set; }
        public int PreferredContactMethod { get; set; }
        public int PreferredSpokenLanguage { get; set; }
        public int PreferredWrittenLanguage { get; set; }
        public int? Religion { get; set; }
        public int? ReportsTo { get; set; }
        public int? Salutation { get; set; }
        public int SalutationCode { get; set; }
        public int? Suffix { get; set; }
        public int? Vcard { get; set; }
        public int? Closing { get; set; }
        public int ClosingCode { get; set; }
        public int? DateOfDeath { get; set; }
        public int? DissolvedAt { get; set; }
        public int? EstablishedAt { get; set; }
        public int? OriginalName { get; set; }
        public int? SearchEmail1 { get; set; }
        public int? SearchEmail2 { get; set; }
        public int? SearchMobile1 { get; set; }
        public int? SearchMobile2 { get; set; }
        public int? SearchPhone1 { get; set; }
        public int? SearchPhone2 { get; set; }
        public string SearchPostal1City { get; set; }
        public int? SearchPostal1Country { get; set; }
        public string SearchPostal1PostalCode { get; set; }
        public int? SearchPostal1State { get; set; }
        public int? SearchPostal1StreetNumber { get; set; }
        public int? SearchPostal2City { get; set; }
        public int? SearchPostal2Country { get; set; }
        public int? SearchPostal2PostalCode { get; set; }
        public int? SearchPostal2State { get; set; }
        public int? SearchPostal2StreetNumber { get; set; }
        public int? SearchPostal1AddressLine { get; set; }
        public int? SearchPostal1Street { get; set; }
        public int? SearchPostal2AddressLine { get; set; }
        public int? SearchPostal2Street { get; set; }
        public string SearchName { get; set; }
        public int? PlaceOfBirth { get; set; }
        public int? PlaceOfDeath { get; set; }
        public int? PlaceOfOrigin { get; set; }
        public int? ActivityTracker { get; set; }
        public int? AdditionalName1 { get; set; }
        public int? AdditionalName2 { get; set; }
        public int? ContractGroup { get; set; }
        public int? DocumentFolder { get; set; }
        public int? GroupType { get; set; }
        public int? CompanyApprenticeshipNo { get; set; }
        public int? CompanyType { get; set; }
        public int? VatNumber { get; set; }
        public int? Institution { get; set; }
        public int? KlassNiveau { get; set; }
        public int? KlassState { get; set; }
        public int? KlassType { get; set; }
        public int? MaxMembers { get; set; }
        public int? MinMembers { get; set; }
        public int? SearchCourseSequences { get; set; }
        public int? SearchEducationLevels { get; set; }
        public int? SearchKlassEndAt { get; set; }
        public int? SearchKlassStartAt { get; set; }
        public int? SearchKlassState { get; set; }
        public int? SearchKlassType { get; set; }
        public int? SearchMemberCountF { get; set; }
        public int? SearchMemberCountM { get; set; }
        public int? SearchMemberCountTotal { get; set; }
        public int? SearchSubjectTables { get; set; }
        public int? SearchTeachers { get; set; }
        public int? AccountingCompanyCode { get; set; }
        public int? DepotHolder { get; set; }
        public int? EsrCodePattern { get; set; }
        public int? CompulsorySchoolAttendanceEndAt { get; set; }
        public int? CompulsorySchoolAttendanceStartAt { get; set; }
        public int? FirstNamePassport { get; set; }
        public int? LastNamePassport { get; set; }
        public int? QualificationType { get; set; }
        public int? RecalculatedAssessmentsAt { get; set; }
        public int? ReligionType { get; set; }
        public int? ResidencePermit { get; set; }
        public int? SearchContractTypes { get; set; }
        public int? SearchOrganisationNames { get; set; }
        public int? SearchQualificationTypes { get; set; }
        public int? SearchDateTime0 { get; set; }
        public int? SearchDateTime1 { get; set; }
        public int? SearchDateTime2 { get; set; }
        public int? SearchDateTime3 { get; set; }
        public int? SearchDateTime4 { get; set; }
        public int? SearchDateTime5 { get; set; }
        public int? SearchDateTime6 { get; set; }
        public int? SearchDateTime7 { get; set; }
        public int? SearchDateTime8 { get; set; }
        public int? SearchDateTime9 { get; set; }
        public int? SearchNumber0 { get; set; }
        public int? SearchNumber1 { get; set; }
        public int? SearchNumber2 { get; set; }
        public int? SearchNumber3 { get; set; }
        public int? SearchNumber4 { get; set; }
        public int? SearchNumber5 { get; set; }
        public int? SearchNumber6 { get; set; }
        public int? SearchNumber7 { get; set; }
        public int? SearchNumber8 { get; set; }
        public int? SearchNumber9 { get; set; }
        public int? SearchString0 { get; set; }
        public int? SearchString1 { get; set; }
        public int? SearchString2 { get; set; }
        public int? SearchString3 { get; set; }
        public int? SearchString4 { get; set; }
        public int? SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public int? SearchString7 { get; set; }
        public int? SearchString8 { get; set; }
        public int? SearchString9 { get; set; }
        public string AccountNumber { get; set; }
        public int? ShisCode { get; set; }
    }
}
