using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Contract
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public DateTime? ActiveOn { get; set; }
        public int Activity { get; set; }
        public string Broker { get; set; }
        public string CalcRule { get; set; }
        public DateTime? CancelOn { get; set; }
        public string Carrier { get; set; }
        public int Category { get; set; }
        public DateTime? ClosedOn { get; set; }
        public int Competitor { get; set; }
        public int Contact { get; set; }
        public short? ContractCurrency { get; set; }
        public short? ContractLanguage { get; set; }
        public string ContractNumber { get; set; }
        public short? ContractState { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public string Customer { get; set; }
        public string Description { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public DateTime? ExpiresOn { get; set; }
        public int ExternalLink { get; set; }
        public string GiftMessage { get; set; }
        public int InventoryCb { get; set; }
        public bool? IsGift { get; set; }
        public int ModifiedBy { get; set; }
        public string Name { get; set; }
        public string Origin { get; set; }
        public int Owner { get; set; }
        public short? PaymentTerms { get; set; }
        public DateTime? PricingDate { get; set; }
        public string PricingRule { get; set; }
        public short? PricingState { get; set; }
        public short? Priority { get; set; }
        public string SalesRep { get; set; }
        public string PParent { get; set; }
        public string ShippingInstructions { get; set; }
        public short? ShippingMethod { get; set; }
        public string ShippingTrackingNumber { get; set; }
        public string Supplier { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? TotalAmountIncludingTax { get; set; }
        public decimal? TotalBaseAmount { get; set; }
        public decimal? TotalDiscountAmount { get; set; }
        public decimal? TotalSalesCommission { get; set; }
        public decimal? TotalTaxAmount { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public decimal? EstimatedSalesCommission { get; set; }
        public short? LeadSource { get; set; }
        public short? LeadRating { get; set; }
        public short? FreightTerms { get; set; }
        public string SubmitStatusDescription { get; set; }
        public DateTime? SubmitDate { get; set; }
        public short? SubmitStatus { get; set; }
        public short? CloseProbability { get; set; }
        public DateTime? EstimatedCloseDate { get; set; }
        public decimal? EstimatedValue { get; set; }
        public string NextStep { get; set; }
        public short? OpportunityRating { get; set; }
        public short? OpportunitySource { get; set; }
        public int? ContractRole { get; set; }
        public bool? ExtBoolean0 { get; set; }
        public bool? ExtBoolean1 { get; set; }
        public bool? ExtBoolean2 { get; set; }
        public bool? ExtBoolean3 { get; set; }
        public bool? ExtBoolean4 { get; set; }
        public short? ExtCode0 { get; set; }
        public short? ExtCode1 { get; set; }
        public short? ExtCode2 { get; set; }
        public short? ExtCode3 { get; set; }
        public short? ExtCode4 { get; set; }
        public DateTime? ExtDate0 { get; set; }
        public DateTime? ExtDate1 { get; set; }
        public DateTime? ExtDate2 { get; set; }
        public DateTime? ExtDate3 { get; set; }
        public DateTime? ExtDate4 { get; set; }
        public DateTime? ExtDateTime0 { get; set; }
        public DateTime? ExtDateTime1 { get; set; }
        public DateTime? ExtDateTime2 { get; set; }
        public DateTime? ExtDateTime3 { get; set; }
        public DateTime? ExtDateTime4 { get; set; }
        public decimal? ExtNumber0 { get; set; }
        public decimal? ExtNumber1 { get; set; }
        public decimal? ExtNumber2 { get; set; }
        public decimal? ExtNumber3 { get; set; }
        public decimal? ExtNumber4 { get; set; }
        public string ExtString0 { get; set; }
        public string ExtString1 { get; set; }
        public string ExtString2 { get; set; }
        public string ExtString3 { get; set; }
        public string ExtString4 { get; set; }
        public string LastAppliedCreator { get; set; }
        public string ContractType { get; set; }
        public string SalesTaxTypeGroup { get; set; }
        public bool? NoAutoRecalc { get; set; }
        public string BmType { get; set; }
        public string DetailedDescription { get; set; }
        public string InvoiceAddressOrigin { get; set; }
        public short? PreferredEducationLevel { get; set; }
        public string PriceLevel { get; set; }
        public string Quote { get; set; }
        public DateTime? SearchStudentBirthdate { get; set; }
        public string SearchStudentFirstName { get; set; }
        public string SearchStudentKlassNames { get; set; }
        public string SearchStudentLastName { get; set; }
        public string SearchStudentPostalCity { get; set; }
        public DateTime? SearchSubjectTableActiveOn { get; set; }
        public DateTime? SearchSubjectTableExpiresOn { get; set; }
        public string SearchSubjectTableName { get; set; }
        public string SearchSubjectTableVersionId { get; set; }
        public string SyllabusStatus { get; set; }
        public string ContractKindType { get; set; }
        public string CourseType { get; set; }
        public string DocumentFolder { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmploymentContractType { get; set; }
        public string ExitReason { get; set; }
        public bool? IsGeneralAgreement { get; set; }
        public string LessonTermType { get; set; }
        public decimal? YearsOfService { get; set; }
        public decimal? YearsOfServiceCorr { get; set; }
        public string YearsOfServiceCorrReason { get; set; }
        public string ApprenticeshipContractType { get; set; }
        public string ApprenticeshipJobType { get; set; }
        public string ApprenticeshipType { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
        public string ExitReasonType { get; set; }
        public DateTime? ApplicationDate { get; set; }
        public int? Correction { get; set; }
        public string EmployeeAliasName { get; set; }
        public DateTime? ValidFrom { get; set; }
        public int? VisibleFor { get; set; }
        public string BiLingualMatura { get; set; }
        public string ExamNumber { get; set; }
        public int? ExamRepetitionCount { get; set; }
        public int? LevelRepetitionCount { get; set; }
        public string MusicSchoolStatisticAllocation { get; set; }
        public string PreCareer { get; set; }
        public string CandidateNumber { get; set; }
    }
}
