using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Activity
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public string ActivityNumber { get; set; }
        public short? ActivityState { get; set; }
        public string ActivityType { get; set; }
        public DateTime? ActualEnd { get; set; }
        public DateTime? ActualStart { get; set; }
        public string AssignedTo { get; set; }
        public int Category { get; set; }
        public int Contract { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public string Description { get; set; }
        public string DetailedDescription { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public DateTime? DueBy { get; set; }
        public int ExternalLink { get; set; }
        public string Ical { get; set; }
        public string LastTransition { get; set; }
        public string Location { get; set; }
        public string Misc1 { get; set; }
        public string Misc2 { get; set; }
        public string Misc3 { get; set; }
        public int ModifiedBy { get; set; }
        public string Name { get; set; }
        public DateTime? OriginalScheduledEnd { get; set; }
        public int Owner { get; set; }
        public short? PercentComplete { get; set; }
        public short? Priority { get; set; }
        public string ProcessState { get; set; }
        public string RepAcct { get; set; }
        public string RepContact { get; set; }
        public DateTime? ScheduledEnd { get; set; }
        public DateTime? ScheduledStart { get; set; }
        public string PParent { get; set; }
        public int? TotalVotes { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public short? CaseOrigin { get; set; }
        public short? CaseType { get; set; }
        public short? CustomerSatisfaction { get; set; }
        public short? Reproducibility { get; set; }
        public short? Severity { get; set; }
        public bool? DeliveryReceiptRequested { get; set; }
        public string MessageBody { get; set; }
        public string MessageSubject { get; set; }
        public bool? ReadReceiptRequested { get; set; }
        public DateTime? SendDate { get; set; }
        public string SenderEmail { get; set; }
        public string Reference { get; set; }
        public string SenderMailing { get; set; }
        public string Sender { get; set; }
        public int Competitor { get; set; }
        public string LastAppliedCreator { get; set; }
        public string Gateway { get; set; }
        public string Document { get; set; }
        public string Template { get; set; }
        public short? IcalType { get; set; }
        public string CreationContext { get; set; }
        public short? IcalClass { get; set; }
        public string InstitutionActivity { get; set; }
        public string AssessmentDefinition { get; set; }
        public int? AssessmentBase { get; set; }
        public decimal? CalculatedGrade { get; set; }
        public DateTime? CalculatedGradeAt { get; set; }
        public short? DocumentClassification { get; set; }
        public decimal? FinalGrade { get; set; }
        public DateTime? FinalGradeAt { get; set; }
        public decimal? LastCalculatedGrade { get; set; }
        public DateTime? LastCalculatedGradeAt { get; set; }
        public DateTime? LockedAt { get; set; }
        public string LockedBy { get; set; }
        public DateTime? ReleasedGradeAt { get; set; }
        public string ReleasedGradeBy { get; set; }
        public decimal? SubmittedGrade { get; set; }
        public DateTime? SubmittedGradeAt { get; set; }
        public string SubmittedGradeBy { get; set; }
        public bool? SubmittedGradeDisabled { get; set; }
        public string SubmittedGradeRemarks { get; set; }
        public short? SubmittedGradeStatus { get; set; }
        public decimal? SubmittedGradeVerify { get; set; }
        public DateTime? SubmittedGradeVerifyAt { get; set; }
        public string SubmittedGradeVerifyBy { get; set; }
        public bool? SubmittedGradeVerifyDisabled { get; set; }
        public string SubmittedGradeVerifyRemarks { get; set; }
        public short? SubmittedGradeVerifyStatus { get; set; }
        public string CourseCode { get; set; }
        public short? CourseFrequency { get; set; }
        public string CourseType { get; set; }
        public int? LessonDurationInMinutes { get; set; }
        public int? MaxParticipants { get; set; }
        public int? MinParticipants { get; set; }
        public int? NumberOfLessonsPerPeriod { get; set; }
        public string SearchCourseSequences { get; set; }
        public string SearchCourseType { get; set; }
        public string SearchEducationLevels { get; set; }
        public int? SearchPartyCountF { get; set; }
        public int? SearchPartyCountM { get; set; }
        public int? SearchPartyCountTotal { get; set; }
        public string SearchProcessState { get; set; }
        public string SearchSubjectTables { get; set; }
        public string SearchSubjects { get; set; }
        public string SearchTeachers { get; set; }
        public string Subject { get; set; }
        public int? TotalNumberOfLessons { get; set; }
        public int? DelayInMinutes { get; set; }
        public string CertificateDefinition { get; set; }
        public string CertificateDocument { get; set; }
        public string DocumentFolder { get; set; }
        public string JournalEntryCategory { get; set; }
        public decimal? ExaminationWeight { get; set; }
        public string GradeCalculator { get; set; }
        public decimal? GradeCalculatorParam0 { get; set; }
        public decimal? GradeCalculatorParam1 { get; set; }
        public decimal? GradeCalculatorParam2 { get; set; }
        public decimal? GradeCalculatorParam3 { get; set; }
        public decimal? GradeCalculatorParam4 { get; set; }
        public decimal? GradeRounding { get; set; }
        public string GradeSystem { get; set; }
        public string ScheduledCourse { get; set; }
        public string SearchScheduledCourse { get; set; }
        public string InvoicingActivityType { get; set; }
        public int? AbsenceCount { get; set; }
        public string AbsenceReason { get; set; }
        public string AbsenceUnit { get; set; }
        public string ApologizeContact { get; set; }
        public DateTime? ApologizeDate { get; set; }
        public string ApologizeState { get; set; }
        public string EducationCertificate { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
        public DateTime? LockedFrom { get; set; }
        public string PresenceReason { get; set; }
        public string ExemptionReason { get; set; }
        public string RecurrenceRule { get; set; }
        public string CalendarActivityType { get; set; }
        public string DisplayColor { get; set; }
        public string Room { get; set; }
        public int? CourseNiveau { get; set; }
        public bool? IsBillable { get; set; }
        public string EducationAppointmentType { get; set; }
        public decimal? CalculatedGrade2 { get; set; }
        public decimal? FinalGrade2 { get; set; }
        public decimal? LastCalculatedGrade2 { get; set; }
        public short? CalculatedGradeStatus { get; set; }
        public DateTime? SoftLockedAt { get; set; }
        public string SoftLockedBy { get; set; }
        public DateTime? SoftLockedFrom { get; set; }
    }
}
