using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Product
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public DateTime? ActiveOn { get; set; }
        public bool? AllowModification { get; set; }
        public bool? AllowRemoval { get; set; }
        public int AlternateProductNumber { get; set; }
        public int Category { get; set; }
        public int Classification { get; set; }
        public string ConfigType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public int? DefaultPositions { get; set; }
        public string DefPriceLevel { get; set; }
        public decimal? DefaultQuantity { get; set; }
        public string DefaultUom { get; set; }
        public string Description { get; set; }
        public string DetailedDescription { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public DateTime? ExpiresOn { get; set; }
        public int ExternalLink { get; set; }
        public decimal? GrossWeightKilogram { get; set; }
        public bool? IsStockItem { get; set; }
        public long? ItemNumber { get; set; }
        public int? MaxPositions { get; set; }
        public decimal? MaxQuantity { get; set; }
        public short? MinMaxQuantityHandling { get; set; }
        public int? MinPositions { get; set; }
        public decimal? MinQuantity { get; set; }
        public int ModifiedBy { get; set; }
        public string Name { get; set; }
        public decimal? NetWeightKilogram { get; set; }
        public decimal? OffsetQuantity { get; set; }
        public int Owner { get; set; }
        public string Picture { get; set; }
        public int PriceUom { get; set; }
        public string ProductDimension { get; set; }
        public string ProductNumber { get; set; }
        public short? ProductState { get; set; }
        public string ProductUsage { get; set; }
        public string SalesTaxType { get; set; }
        public string PParent { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public string Profile { get; set; }
        public string Version { get; set; }
        public bool? ExtBoolean0 { get; set; }
        public bool? ExtBoolean1 { get; set; }
        public bool? ExtBoolean2 { get; set; }
        public bool? ExtBoolean3 { get; set; }
        public bool? ExtBoolean4 { get; set; }
        public short? ExtCode0 { get; set; }
        public short? ExtCode1 { get; set; }
        public short? ExtCode2 { get; set; }
        public short? ExtCode3 { get; set; }
        public short? ExtCode4 { get; set; }
        public DateTime? ExtDate0 { get; set; }
        public DateTime? ExtDate1 { get; set; }
        public DateTime? ExtDate2 { get; set; }
        public DateTime? ExtDate3 { get; set; }
        public DateTime? ExtDate4 { get; set; }
        public DateTime? ExtDateTime0 { get; set; }
        public DateTime? ExtDateTime1 { get; set; }
        public DateTime? ExtDateTime2 { get; set; }
        public DateTime? ExtDateTime3 { get; set; }
        public DateTime? ExtDateTime4 { get; set; }
        public decimal? ExtNumber0 { get; set; }
        public decimal? ExtNumber1 { get; set; }
        public decimal? ExtNumber2 { get; set; }
        public decimal? ExtNumber3 { get; set; }
        public decimal? ExtNumber4 { get; set; }
        public string ExtString0 { get; set; }
        public string ExtString1 { get; set; }
        public string ExtString2 { get; set; }
        public string ExtString3 { get; set; }
        public string ExtString4 { get; set; }
        public string DepotAssignmentGroup { get; set; }
        public string DocumentFolder { get; set; }
        public string FemaleDiplomaTitle { get; set; }
        public string GradeSystem { get; set; }
        public string MaleDiplomaTitle { get; set; }
        public string ProfessionMaturityType { get; set; }
        public string Education { get; set; }
        public string BmType { get; set; }
        public bool? CheckConditionOfAdmission { get; set; }
        public decimal? DefaultGradeRounding { get; set; }
        public int? DefaultMaxKlassSize { get; set; }
        public int? DefaultMaxParticipants { get; set; }
        public int? DefaultMinParticipants { get; set; }
        public string EducationType { get; set; }
        public string ExaminationType { get; set; }
        public string SearchEducationName { get; set; }
        public string SearchEducationType { get; set; }
        public int? SearchNumberOfApplications { get; set; }
        public string SubjectTableStatus { get; set; }
        public string VersionId { get; set; }
        public short? CourseFrequency { get; set; }
        public int? CourseNiveau { get; set; }
        public string CourseSequence { get; set; }
        public string DisplayColor { get; set; }
        public string DivisionType { get; set; }
        public int? DurationInMinutes { get; set; }
        public bool? IgnoreAbsencePeriod { get; set; }
        public int? NumberOfLessons { get; set; }
        public string Subject { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectGroup { get; set; }
        public string SubjectTable { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
        public string GraduationPromotion { get; set; }
        public DateTime? ExamDate { get; set; }
        public string InternalUnit { get; set; }
        public int? MinNumberOfExaminations { get; set; }
        public string GroupOfferedCourse { get; set; }
        public DateTime? RegistrationDeadline { get; set; }
        public bool? TrackStudentAbsences { get; set; }
        public bool? TrackStudentAssessments { get; set; }
        public bool? TrackStudentPresences { get; set; }
        public bool? TrackTeacherWorkRecords { get; set; }
        public string KlassForm { get; set; }
        public string LessonType { get; set; }
        public short? ExaminationPlanningType { get; set; }
        public decimal? DefaultGradeRounding2 { get; set; }
        public string DefaultKlassNiveau { get; set; }
    }
}
