using System;
using System.Collections.Generic;

namespace CoreDbSpCall.Models.DB
{
    public partial class Oocke1Modelelement
    {
        public string ObjectId { get; set; }
        public short? AccessLevelBrowse { get; set; }
        public short? AccessLevelDelete { get; set; }
        public short? AccessLevelUpdate { get; set; }
        public string Annotation { get; set; }
        public int Category { get; set; }
        public string Container { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public bool? Disabled { get; set; }
        public string DisabledReason { get; set; }
        public int? ElementOrder { get; set; }
        public int ExternalLink { get; set; }
        public int ModifiedBy { get; set; }
        public string Name { get; set; }
        public int Owner { get; set; }
        public string QualifiedName { get; set; }
        public string PParent { get; set; }
        public int Stereotype { get; set; }
        public bool? UserBoolean0 { get; set; }
        public bool? UserBoolean1 { get; set; }
        public bool? UserBoolean2 { get; set; }
        public bool? UserBoolean3 { get; set; }
        public int UserBoolean4 { get; set; }
        public short? UserCode0 { get; set; }
        public short? UserCode1 { get; set; }
        public short? UserCode2 { get; set; }
        public short? UserCode3 { get; set; }
        public int UserCode4 { get; set; }
        public DateTime? UserDate0 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public int UserDate4 { get; set; }
        public DateTime? UserDateTime0 { get; set; }
        public DateTime? UserDateTime1 { get; set; }
        public DateTime? UserDateTime2 { get; set; }
        public DateTime? UserDateTime3 { get; set; }
        public int UserDateTime4 { get; set; }
        public decimal? UserNumber0 { get; set; }
        public decimal? UserNumber1 { get; set; }
        public decimal? UserNumber2 { get; set; }
        public decimal? UserNumber3 { get; set; }
        public int UserNumber4 { get; set; }
        public string UserString0 { get; set; }
        public string UserString1 { get; set; }
        public string UserString2 { get; set; }
        public string UserString3 { get; set; }
        public int UserString4 { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Dtype { get; set; }
        public int? MaxLength { get; set; }
        public short? Multiplicity { get; set; }
        public string Type { get; set; }
        public int? UpperBound { get; set; }
        public string ExposedEnd { get; set; }
        public bool? IsChangeable { get; set; }
        public string ReferencedEnd { get; set; }
        public short? Scope { get; set; }
        public short? Visibility { get; set; }
        public string TagValue { get; set; }
        public bool? IsAbstract { get; set; }
        public int Supertype { get; set; }
        public int Exception { get; set; }
        public bool? IsQuery { get; set; }
        public string Semantics { get; set; }
        public string ConstValue { get; set; }
        public bool? IsSingleton { get; set; }
        public bool? IsDerived { get; set; }
        public bool? IsClustered { get; set; }
        public string Namespace { get; set; }
        public int Label { get; set; }
        public short? Direction { get; set; }
        public short? Aggregation { get; set; }
        public bool? IsNavigable { get; set; }
        public int QualifierName { get; set; }
        public int QualifierType { get; set; }
        public short? EvaluationPolicy { get; set; }
        public string Expression { get; set; }
        public string Language { get; set; }
        public DateTime? SearchDateTime0 { get; set; }
        public DateTime? SearchDateTime1 { get; set; }
        public DateTime? SearchDateTime2 { get; set; }
        public DateTime? SearchDateTime3 { get; set; }
        public DateTime? SearchDateTime4 { get; set; }
        public DateTime? SearchDateTime5 { get; set; }
        public DateTime? SearchDateTime6 { get; set; }
        public DateTime? SearchDateTime7 { get; set; }
        public DateTime? SearchDateTime8 { get; set; }
        public DateTime? SearchDateTime9 { get; set; }
        public decimal? SearchNumber0 { get; set; }
        public decimal? SearchNumber1 { get; set; }
        public decimal? SearchNumber2 { get; set; }
        public decimal? SearchNumber3 { get; set; }
        public decimal? SearchNumber4 { get; set; }
        public decimal? SearchNumber5 { get; set; }
        public decimal? SearchNumber6 { get; set; }
        public decimal? SearchNumber7 { get; set; }
        public decimal? SearchNumber8 { get; set; }
        public decimal? SearchNumber9 { get; set; }
        public string SearchString0 { get; set; }
        public string SearchString1 { get; set; }
        public string SearchString2 { get; set; }
        public string SearchString3 { get; set; }
        public string SearchString4 { get; set; }
        public string SearchString5 { get; set; }
        public string SearchString6 { get; set; }
        public string SearchString7 { get; set; }
        public string SearchString8 { get; set; }
        public string SearchString9 { get; set; }
    }
}
